# Recreate NEP7 Grid

The goal of this script is to match the NEP7 using functions found within spherical.py and gridUtils.py

In [77]:
import numpy 

# define spherical python functions
def angle_through_center(p1, p2):
    """Angle at center of sphere between two points on the surface of the sphere.
    Positions are given as (latitude,longitude) tuples measured in degrees."""
    phi1 = numpy.deg2rad( p1[0] )
    phi2 = numpy.deg2rad( p2[0] )
    dphi_2 = 0.5 * ( phi2 - phi1 )
    dlambda_2 = 0.5 * numpy.deg2rad( p2[1] - p1[1] )
    a = numpy.sin( dphi_2 )**2 + numpy.cos( phi1 ) * numpy.cos( phi2 ) * ( numpy.sin( dlambda_2 )**2 )
    c = 2. * numpy.arctan2( numpy.sqrt(a), numpy.sqrt( 1. - a ) )
    return c

def quad_area(lat, lon):
    """Returns area of spherical quad (bounded by great arcs)."""
    # x,y,z are 3D coordinates
    d2r = numpy.deg2rad(1.)
    x = numpy.cos(d2r * lat) * numpy.cos(d2r * lon)
    y = numpy.cos(d2r * lat) * numpy.sin(d2r * lon)
    z = numpy.sin(d2r * lat)
    c0 = (x[ :-1, :-1], y[ :-1, :-1], z[ :-1, :-1])
    c1 = (x[ :-1,1:  ], y[ :-1,1:  ], z[ :-1,1:  ])
    c2 = (x[1:  ,1:  ], y[1:  ,1:  ], z[1:  ,1:  ])
    c3 = (x[1:  , :-1], y[1:  , :-1], z[1:  , :-1])
    a0 = angle_between(c1, c0, c2)
    a1 = angle_between(c2, c1, c3)
    a2 = angle_between(c3, c2, c0)
    a3 = angle_between(c0, c3, c1)
    return a0 + a1 + a2 + a3 - 2. * numpy.pi

def angle_between(v1, v2, v3):
    """Returns angle v2-v1-v3 i.e betweeen v1-v2 and v1-v3."""
    # vector product between v1 and v2
    px = v1[1] * v2[2] - v1[2] * v2[1]
    py = v1[2] * v2[0] - v1[0] * v2[2]
    pz = v1[0] * v2[1] - v1[1] * v2[0]
    # vector product between v1 and v3
    qx = v1[1] * v3[2] - v1[2] * v3[1]
    qy = v1[2] * v3[0] - v1[0] * v3[2]
    qz = v1[0] * v3[1] - v1[1] * v3[0]

    ddd = (px * px + py * py + pz * pz) * (qx * qx + qy * qy + qz * qz)
    ddd = (px * qx + py * qy + pz * qz) / numpy.sqrt(ddd)
    angle = numpy.arccos( ddd )
    return angle



In [78]:
# load gridUtils functions

def generate_regional_spherical(lon0, lon_span, lat0, lat_span, tilt, refine):
    """Generate a regional grid centered at (lon0,lat0) with spans of (lon_span,lat_span) and tilted by angle tilt"""
    Ni = int(lon_span*refine)
    Nj = int(lat_span*refine)

    #Generate a mesh at equator centered at (lon0, 0)
    lam_,phi_ = generate_latlon_mesh_centered(Ni,Nj,lon0,lon_span,0.0,lat_span)
    lam_,phi_ = rotate_z_mesh(lam_,phi_, (90.-lon0)*PI_180)  #rotate around z to bring it centered at y axis
    lam_,phi_ = rotate_y_mesh(lam_,phi_,tilt*PI_180)         #rotate around y axis to tilt it as desired
    lam_,phi_ = rotate_x_mesh(lam_,phi_,lat0*PI_180)         #rotate around x to bring it centered at (lon0,lat0)
    lam_,phi_ = rotate_z_mesh(lam_,phi_,-(90.-lon0)*PI_180)  #rotate around z to bring it back

    return lam_,phi_

def rotate_x(x,y,z,theta):
    """Rotate vector (x,y,z) by angle theta around x axis."""
    """Returns the rotated components."""
    cost = np.cos(theta)
    sint = np.sin(theta)
    yp   = y*cost - z*sint
    zp   = y*sint + z*cost
    return x,yp,zp

def rotate_y(x,y,z,theta):
    """Rotate vector (x,y,z) by angle theta around y axis."""
    """Returns the rotated components."""
    cost = np.cos(theta)
    sint = np.sin(theta)
    zp   = z*cost - x*sint
    xp   = z*sint + x*cost
    return xp,y,zp

def rotate_z(x,y,z,theta):
    """Rotate vector (x,y,z) by angle theta around z axis."""
    """Returns the rotated components."""
    cost = np.cos(theta)
    sint = np.sin(theta)
    xp   = x*cost - y*sint
    yp   = x*sint + y*cost
    return xp,yp,z

def pol2cart(lam,phi):
    """Transform a point on globe from Polar (lam,phi) to Cartesian coordinates."""
    """Returns the Cartesian coordinates"""
    lam=lam*PI_180
    phi=phi*PI_180
    x=np.cos(phi)*np.cos(lam)
    y=np.cos(phi)*np.sin(lam)
    z=np.sin(phi)
    return x,y,z
    
def cart2pol(x,y,z):
    """Transform a point on globe from Cartesian (x,y,z) to polar coordinates."""
    """Returns the polar coordinates"""
    lam=np.arctan2(y,x)/PI_180
    phi=np.arctan(z/np.sqrt(x**2+y**2))/PI_180
    return lam,phi

def rotate_z_mesh(lam,phi,theta):
    """Rotate the whole mesh on globe by angle theta around z axis (globe polar axis)."""
    """Returns the rotated mesh."""
    #Bring the angle to be in [-pi,pi] so that atan2 would work
    lam       = np.where(lam>180,lam-360,lam)
    #Change to Cartesian coord
    x,y,z     = pol2cart(lam,phi)
    #Rotate
    xp,yp,zp  = rotate_z(x,y,z,theta)
    #Change back to polar coords using atan2, in [-pi,pi]
    lamp,phip = cart2pol(xp,yp,zp)
    #Bring the angle back to be in [0,2*pi]
    lamp      = np.where(lamp<0,lamp+360,lamp)
    return lamp,phip

def rotate_x_mesh(lam,phi,theta):
    """Rotate the whole mesh on globe by angle theta around x axis (passing through equator and prime meridian.)."""
    """Returns the rotated mesh."""
    #Bring the angle to be in [-pi,pi] so that atan2 would work
    lam       = np.where(lam>180,lam-360,lam)
    #Change to Cartesian coord
    x,y,z     = pol2cart(lam,phi)
    #Rotate
    xp,yp,zp  = rotate_x(x,y,z,theta)
    #Change back to polar coords using atan2, in [-pi,pi]
    lamp,phip = cart2pol(xp,yp,zp)
    #Bring the angle back to be in [0,2*pi]
    lamp      = np.where(lamp<0,lamp+360,lamp)
    return lamp,phip

def rotate_y_mesh(lam,phi,theta):
    """Rotate the whole mesh on globe by angle theta around y axis (passing through equator and prime meridian+90.)."""
    """Returns the rotated mesh."""
    #Bring the angle to be in [-pi,pi] so that atan2 would work
    lam       = np.where(lam>180,lam-360,lam)
    #Change to Cartesian coord
    x,y,z     = pol2cart(lam,phi)
    #Rotate
    xp,yp,zp  = rotate_y(x,y,z,theta)
    #Change back to polar coords using atan2, in [-pi,pi]
    lamp,phip = cart2pol(xp,yp,zp)
    #Bring the angle back to be in [0,2*pi]
    lamp      = np.where(lamp<0,lamp+360,lamp)
    return lamp,phip

def generate_latlon_mesh_centered(lni, lnj, llon0, llen_lon, llat0, llen_lat, ensure_nj_even=True):
    """Generate a regular lat-lon grid"""
    msg = 'Generating regular lat-lon grid centered at %.2f %.2f on equator.' % (llon0, llat0)

    llonSP = llon0 - llen_lon/2 + np.arange(lni+1) * llen_lon/float(lni)
    llatSP = llat0 - llen_lat/2 + np.arange(lnj+1) * llen_lat/float(lnj)
    if(llatSP.shape[0]%2 == 0 and ensure_nj_even):
        llatSP = np.delete(llatSP,0,0)
    llamSP = np.tile(llonSP,(llatSP.shape[0],1))
    lphiSP = np.tile(llatSP.reshape((llatSP.shape[0],1)),(1,llonSP.shape[0]))
    msg = '   Generated regular lat-lon grid between latitudes %.2f %.2f' % (lphiSP[0,0],lphiSP[-1,0])

    msg = '   Number of js=%d' % (lphiSP.shape[0])

    #h_i_inv=llen_lon*self.PI_180*np.cos(lphiSP*self.PI_180)/lni
    #h_j_inv=llen_lat*self.PI_180*np.ones(lphiSP.shape)/lnj
    #delsin_j = np.roll(np.sin(lphiSP*self.PI_180),shift=-1,axis=0) - np.sin(lphiSP*self.PI_180)
    #dx_h=h_i_inv[:,:-1]*self._default_Re
    #dy_h=h_j_inv[:-1,:]*self._default_Re
    #area=delsin_j[:-1,:-1]*self._default_Re*self._default_Re*llen_lon*self.self.PI_180/lni
    return llamSP,lphiSP


### Create Test Values

In [121]:
# define test values
import numpy as np

PI_180 = np.pi/180.
dx = 20
dy = 30

x = np.linspace(300,310,dx)
y = np.linspace(10, 20, dy)
R = 6370.e3 # Radius of sphere        
lon0 = 305
lat0=15
tilt=0
refine=2

# test successful

In [120]:
#dx,dy, x,y,lon0,lat0

### Load NEP7 Grid

In [80]:
# read in nep7 parameters
import xarray as xr

nep7 = xr.open_dataset("/Users/james/Documents/Github/esm_lab/gridtools/nep7_grid/ocean_hgrid.nc")
nep7

<xarray.Dataset>
Dimensions:   (nx: 684, nxp: 685, ny: 1632, nyp: 1633)
Dimensions without coordinates: nx, nxp, ny, nyp
Data variables:
    x         (nyp, nxp) float32 ...
    y         (nyp, nxp) float32 ...
    dx        (nyp, nx) float32 ...
    dy        (ny, nxp) float32 ...
    area      (ny, nx) float32 ...
    angle_dx  (nyp, nxp) float32 ...
    tile      |S5 ...
Attributes:
    grid_version:  0.2
    code_version:  ESMG/PyCNAL: heads/python3-0-gb0204bf2e5-dirty
    history:       2020-06-30: convert_ROMS_grid_to_MOM6.py /import/AKWATERS/...

In [127]:
nep7.x.values[-1,:].shape

(685,)

In [139]:
# redefine for nep7 grid

PI_180 = np.pi/180.
dx = len(nep7.x.values[-1,:])
dy = len(nep7.y.values[:,-1])

x = np.linspace(np.min(nep7.x), np.max(nep7.x),dx)
y = np.linspace(np.min(nep7.y), np.max(nep7.y),dy)
R = 6370.e3 # Radius of sphere        
lon0 = np.float(np.abs((np.max(nep7.x) + np.min(nep7.x))) / 2)
lat0=np.float(np.abs((np.max(nep7.y) - np.min(nep7.y))) / 2)
tilt=0
refine=1

In [140]:
np.float(np.abs((np.max(nep7.x) + np.min(nep7.x))) / 2)

0.00030517578125

In [141]:
dx,dy, x,y,lon0,lat0

(685,
 1633,
 array([-1.79999939e+02, -1.79473624e+02, -1.78947310e+02, -1.78420995e+02,
        -1.77894680e+02, -1.77368365e+02, -1.76842051e+02, -1.76315736e+02,
        -1.75789421e+02, -1.75263106e+02, -1.74736792e+02, -1.74210477e+02,
        -1.73684162e+02, -1.73157848e+02, -1.72631533e+02, -1.72105218e+02,
        -1.71578903e+02, -1.71052589e+02, -1.70526274e+02, -1.69999959e+02,
        -1.69473645e+02, -1.68947330e+02, -1.68421015e+02, -1.67894700e+02,
        -1.67368386e+02, -1.66842071e+02, -1.66315756e+02, -1.65789442e+02,
        -1.65263127e+02, -1.64736812e+02, -1.64210497e+02, -1.63684183e+02,
        -1.63157868e+02, -1.62631553e+02, -1.62105239e+02, -1.61578924e+02,
        -1.61052609e+02, -1.60526294e+02, -1.59999980e+02, -1.59473665e+02,
        -1.58947350e+02, -1.58421035e+02, -1.57894721e+02, -1.57368406e+02,
        -1.56842091e+02, -1.56315777e+02, -1.55789462e+02, -1.55263147e+02,
        -1.54736832e+02, -1.54210518e+02, -1.53684203e+02, -1.53157888e+02,

In [142]:
len(x)

685

### Make Grid

In [143]:
lonGrid, latGrid = generate_regional_spherical(lon0=lon0, lon_span=dx, lat0=lat0, lat_span=dy, tilt=tilt, refine=refine)
lonGrid

array([[356.67523437, 356.49512248, 356.31661809, ...,   3.68399227,
          3.50548787,   3.32537598],
       [357.35438884, 357.21045134, 357.0676982 , ...,   2.93291215,
          2.79015901,   2.64622152],
       [357.99702056, 357.88762232, 357.77905534, ...,   2.22155502,
          2.11298803,   2.0035898 ],
       ...,
       [182.13443308, 182.25335034, 182.37176218, ..., 177.62884818,
        177.74726002, 177.86617727],
       [182.55553763, 182.6981491 , 182.8401931 , ..., 177.16041726,
        177.30246125, 177.44507273],
       [182.96024794, 183.12569029, 183.29051534, ..., 176.71009501,
        176.87492006, 177.04036241]])

In [144]:
(nxp, nyp) = lonGrid.shape
grid_x= lonGrid
grid_y = latGrid

### Compute Grid Metrics

In [145]:

            
# Make a copy of the lon grid as values are changed for computation
lon = grid_x.copy()
lat = grid_y
        
        # Approximate edge lengths as great arcs
grid_dx  = R * angle_through_center( (lat[ :,1:],lon[ :,1:]), (lat[:  ,:-1],lon[:  ,:-1]) )
grid_dy = R * angle_through_center( (lat[1:, :],lon[1:, :]), (lat[:-1,:  ],lon[:-1,:  ]) )

# Scaling by latitude?
cos_lat = np.cos(np.radians(lat))

# Presize the angle_dx array
angle_dx = np.zeros(lat.shape)
# Fix lon so they are 0 to 360 for computation of angle_dx
lon = np.where(lon < 0., lon+360, lon)
angle_dx[:,1:-1] = np.arctan2( (lat[:,2:] - lat[:,:-2]) , ((lon[:,2:] - lon[:,:-2]) * cos_lat[:,1:-1]) )
angle_dx[:, 0  ] = np.arctan2( (lat[:, 1] - lat[:, 0 ]) , ((lon[:, 1] - lon[:, 0 ]) * cos_lat[:, 0  ]) )
angle_dx[:,-1  ] = np.arctan2( (lat[:,-1] - lat[:,-2 ]) , ((lon[:,-1] - lon[:,-2 ]) * cos_lat[:,-1  ]) )


area = R * R * quad_area(lat, lon)


### Validate

In [153]:
area[:,:-1].shape

(1632, 684)

In [147]:
nep7.area.shape

(1632, 684)

In [148]:
area

array([[1.07721477e+09, 1.07721477e+09, 1.07721477e+09, ...,
        1.07721477e+09, 1.07721477e+09, 1.07721477e+09],
       [8.62165659e+08, 8.62165659e+08, 8.62165659e+08, ...,
        8.62165659e+08, 8.62165659e+08, 8.62165659e+08],
       [6.46854040e+08, 6.46854040e+08, 6.46854040e+08, ...,
        6.46854040e+08, 6.46854040e+08, 6.46854040e+08],
       ...,
       [8.62165659e+08, 8.62165659e+08, 8.62165659e+08, ...,
        8.62165659e+08, 8.62165659e+08, 8.62165659e+08],
       [1.07721477e+09, 1.07721477e+09, 1.07721477e+09, ...,
        1.07721477e+09, 1.07721477e+09, 1.07721477e+09],
       [1.29193590e+09, 1.29193590e+09, 1.29193590e+09, ...,
        1.29193590e+09, 1.29193590e+09, 1.29193590e+09]])

In [150]:
nep7.area.values

array([[16991296., 16997952., 17004604., ..., 20201348., 20203766.,
        20206176.],
       [17002518., 17009178., 17015834., ..., 20213982., 20216400.,
        20218810.],
       [17013740., 17020404., 17027064., ..., 20226610., 20229028.,
        20231440.],
       ...,
       [25758958., 25757898., 25756804., ..., 16411003., 16383695.,
        16356341.],
       [25758890., 25757826., 25756730., ..., 16405458., 16378123.,
        16350743.],
       [25758822., 25757756., 25756658., ..., 16399991., 16372631.,
        16345226.]], dtype=float32)

In [156]:
nep7.area.values - area[:,:-1]

array([[-1.06022348e+09, -1.06021682e+09, -1.06021017e+09, ...,
        -1.05701342e+09, -1.05701101e+09, -1.05700860e+09],
       [-8.45163141e+08, -8.45156481e+08, -8.45149825e+08, ...,
        -8.41951677e+08, -8.41949259e+08, -8.41946849e+08],
       [-6.29840300e+08, -6.29833636e+08, -6.29826976e+08, ...,
        -6.26627430e+08, -6.26625012e+08, -6.26622600e+08],
       ...,
       [-8.36406701e+08, -8.36407761e+08, -8.36408855e+08, ...,
        -8.45754656e+08, -8.45781964e+08, -8.45809318e+08],
       [-1.05145588e+09, -1.05145695e+09, -1.05145804e+09, ...,
        -1.06080931e+09, -1.06083665e+09, -1.06086403e+09],
       [-1.26617708e+09, -1.26617815e+09, -1.26617925e+09, ...,
        -1.27553591e+09, -1.27556327e+09, -1.27559068e+09]])